yarnPath: .yarn/releases/yarn-4.0.0-rc.11.cjs
packageExtensions:
  eslint-config-xo-typescript@*:
    dependencies:
      "@typescript-eslint/parser": '*'
  chalk@*:
    dependencies:
      "#ansi-styles": npm:ansi-styles@6.1.0
      "#supports-color": npm:supports-color@9.2.2
