yarnPath: .yarn/releases/yarn-4.0.0-rc.14.cjs
nodeLinker: pnp
pnpEnableEsmLoader: true
pnpMode: loose
npmScopes:
  adi-ctx:
    npmRegistryServer: 'https://npm.pkg.github.com'
    npmAlwaysAuth: true
    npmAuthToken: ${GITHUB_PERSONAL_ACCESS_TOKEN}
packageExtensions:
  eslint-config-xo-typescript@*:
    dependencies:
      '@typescript-eslint/parser': '*'
  chalk@*:
    dependencies:
      '#ansi-styles': npm:ansi-styles@6.1.0
      '#supports-color': npm:supports-color@9.2.2
  vite@*:
    dependencies:
      supports-color: '*'
  debug@*:
    dependencies:
      supports-color: '*'
